-- Affects FormEdit.lua
FORM = "Form "
TESTING = "Testing "
FORM_1 = " form..."
TESTING_COMPLETED = "Testing completed."

TAB_OVERVIEW_1 = "Overview"
TAB_OVERVIEW_2 = "LazyScript is a scripting language for World of Warcraft that is able to execute certain attacks or abilities under conditions that you specify. This is accomplished by writing a \"form\", which consists of a series of actions and criteria. When the LazyScript macro is run, the LazyScript engine will read through the list of actions from top to bottom until it finds an action that is ready to be used and then executes it."
TAB_OVERVIEW_3 = "Any line may be commented out by placing '--', '//', or '#' at the start of the line."
TAB_OVERVIEW_TUTORIAL_1_1 = "Tutorial 1: Baby steps"
TAB_OVERVIEW_TUTORIAL_1_2 = "For example, let us make LazyScript execute Sinister Strike. First, check what the short name is for Sinister Strike in the actions tab. We see that it is \"ss\". Now choose \"Create New Form\" from the LazyScript minimap menu. Give your form a name like \"MyForm\" and type:" 
TAB_OVERVIEW_TUTORIAL_1_3 = "Click on the \"Test\" button. If everything is okay and there were no typos, a \"Testing completed\" message will appear in your chat box. If there were errors, a summary of the error will be printed in the chat box instead. If everything is working then click on the \"Okay\" button. You should now see the form \"MyForm\" in the LazyScript minimap form list. Click on \"MyForm\" to set it as the default. A little check mark should appear next to \"MyForm\" on the minimap menu."
TAB_OVERVIEW_TUTORIAL_1_4 = "Now create a macro with the command:"
TAB_OVERVIEW_TUTORIAL_1_5 = "and place it on your action bar. Also place the highest rank of \"Sinister Strike\" on your action bar somewhere. The \"Sinister Strike\" action need not be visible. Now go out and fight something and hit your LazyScript macro key and LazyScript will automatically execute Sinister Strike."
TAB_OVERVIEW_TUTORIAL_2_1 = "Tutorial 2: Now we're getting somewhere"
TAB_OVERVIEW_TUTORIAL_2_2 = "|cffffaaff\"That's not particularly impressive\"|r"
TAB_OVERVIEW_TUTORIAL_2_3 = "Well, let us move onto something more interesting then. Let us include an action that we can not execute all the time like \"Riposte\". We always prefer to execute riposte rather than sinister strike, but riposte is not always usable. Edit \"MyForm\" and add riposte before sinister strike, like so:"
TAB_OVERVIEW_TUTORIAL_2_4 = "and place Riposte on your action bar somewhere. Now when you hit the LazyScript macro during combat, LazyScript will execute Sinister Strike until you parry an attack. Once that happens, LazyScript will execute Riposte when you next hit the LazyScript macro button. Most importantly, it will do all this without the \"That action is not ready yet\" spam that you would normally have to put up with when using a standard macro."
TAB_OVERVIEW_TUTORIAL_3_1 = "Tutorial 3: To do or not to do, that is the question"
TAB_OVERVIEW_TUTORIAL_3_2 = "One of the most useful features of LazyScript is the ability to associate conditions or criteria with a particular action. For example, you only want to kick the target if it is casting a spell. Looking at the criteria tab we notice that there is a condition \"-if[Not]TargetIsCasting\" plus some other scary looking stuff. Let us ignore the complicated stuff for now and just use \"-ifTargetIsCasting\". Interrupting a spell is more important than using Riposte, so edit \"MyForm\" and change it to:"
TAB_OVERVIEW_TUTORIAL_3_3 = "Now LazyScript will only kick if it detects that the target is casting a spell."
TAB_OVERVIEW_TUTORIAL_3_4 = "|cffffaaff\"But what if I only want to interrupt fire spells?\"|r"
TAB_OVERVIEW_TUTORIAL_3_5 = "Well that is what the rest of that complicated string is all about. Edit \"MyForm\" and change the form to:"
TAB_OVERVIEW_TUTORIAL_3_6 = "|cffffaaff\"What about if I only want to interrupt fire or frost spells? Do I have to type that all out again?\"|r"
TAB_OVERVIEW_TUTORIAL_3_7 = "Nope, change \"MyForm\" to:"
TAB_OVERVIEW_TUTORIAL_3_8 = "|cffffaaff\"I'm decked out in MC gear. The only spells I care about interrupting are heals. Darn priests... *mutter*\"|r"
TAB_OVERVIEW_TUTORIAL_3_9 = "We have that covered too. Just use the full text string, correctly capitalized with spaces:"
TAB_OVERVIEW_TUTORIAL_4_1 = "Tutorial 4: Why'd you have to go and make things so complicated?"
TAB_OVERVIEW_TUTORIAL_4_2 = "Probably the most complex criteria you will come across are the buff/debuff checking criteria. They are so complex because they are so flexible. For instance, if you only want to renew your Slice and Dice if you do not already have it running. First check the Buff/Debuff tab and find out what the short buff/debuff name is for Slice and Dice. It is \"snd\", so add a line to your form that has:"
TAB_OVERVIEW_TUTORIAL_4_3 = "If you only want to use Rupture on your target if it does not already have rupture active:"
TAB_OVERVIEW_TUTORIAL_4_4 = "|cffffaaff\"Why don't I see buff/debuff xyz in your list?\"|r"
TAB_OVERVIEW_TUTORIAL_4_5 = "Although we try to be as thorough as possible with class abilities, if we were to have entries for every single buff in the game it would take up too much memory. If a buff is not in the list of recognised buffs/debuffs it is still possible to search for the title of the buff. Just use the following criteria and type in the full name of the buff or debuff with capitalization and spacing as it appears in the tooltip text:"
TAB_OVERVIEW_TUTORIAL_4_6 = "|cffffaaff\"My tanks are boring and they tell me not to start attacking the mob until they've sundered it a few times. Can LazyScript help me?\"|r"
TAB_OVERVIEW_TUTORIAL_4_7 = "LazyScript is also able to check how many applications of a buff or debufff there are. After prying out that by \"few\" they mean \"at least 3\", you can add something like this to the top of your form:"
TAB_OVERVIEW_TUTORIAL_5_1 = "Tutorial 5: Multi-tasking"
TAB_OVERVIEW_TUTORIAL_5_2 = "By now you may have noticed that some actions on the actions tab are colored green. Hopefully you read the help text and know that this has something to with multiple actions that do not trigger the global cooldown. What it boils down to is that you can chain any number of these actions together in one line along with at most one action that does trigger the global cooldown and LazyScript will execute them in sequence. For example, activate Cold Blood, use Eviscerate and provide a cute parting message:"
TAB_OVERVIEW_TUTORIAL_5_3 = "Here are a few more examples"
TAB_OVERVIEW_TUTORIAL_6_1 = "Tutorial 6: Form re-use"
TAB_OVERVIEW_TUTORIAL_6_2 = "So you've written some forms and they're starting to get a little long and complicated. If they contain sections which are identical, you can separate that section out into another form and use |cffff770CincludeForm|r to include it in the other forms. For example:"
TAB_OVERVIEW_TUTORIAL_6_FORM_INT = "Form \"Interrupts\":"
TAB_OVERVIEW_TUTORIAL_6_FORM_FA = "Form \"FrontAttack\":"
TAB_OVERVIEW_TUTORIAL_6_FORM_BA = "Form \"BehindAttack\":"
TAB_OVERVIEW_TUTORIAL_6_3 = "This will include the Interrupts form at the beginning of both the FrontAttack and BehindAttack forms as if you had copy and pasted it in there. When you change the contents of the Interrupts form, it will automatically update the FrontAttack and BehindAttack forms to include the new version."
TAB_OVERVIEW_TUTORIAL_6_4 = "|cffffff00Note:|r Be careful that you don't try to include a form into itself, or try to include a form which includes the first form (A includes B includes A). Those will cause a stack overflow error because they're infinite recursion loops."
TAB_OVERVIEW_TUTORIAL_6_5 = "Now perhaps you have some actions that you only want to perform under certain conditions but don't want the whole list of actions to be checked every time you press your LazyScript button. If we look at the previous example, we can see that ifTargetIsCasting is a criteria common to all of the actions in the Interrupts form. Using callForm we could rewrite the previous example like so:"
TAB_OVERVIEW_TUTORIAL_6_6 = "With these changes, when you execute FrontAttack or BehindAttack, it will call the Interrupts form only if the target is casting and not stunned. So if the target is not casting, it won't even check any of the actions/criteria in the Interrupts form."

TAB_LIST_ACTIONS = "List of known Spells/Actions"
TAB_ACTIONS_SYNTAX_SPECIFIC_SPELL_RANK = "<BR/>A specific spell rank can be directed at a particular unit using the syntax:"
TAB_ACTIONS_SYNTAX_SPECIFIC_SPELL_RANK_1 = "<BR/>The |cff00ffff&lt;UnitId&gt;|r can be any valid UnitId sequence as described in &lt;|cff8080ffhttp://www.wowwiki.com/UnitId|r&gt;. For example, @player, @pet, @target, @targettarget. Note that the rank of the spell must always appear before the '@' symbol."
TAB_ACTIONS_GREEN_ACTIONS = "<BR/>Actions in |cff40ff40green|r do not trigger the global cooldown. LazyScript is able to perform multiple of these actions on a single line provided that the line has at most one action that triggers the global cooldown.<BR/>"
TAB_ACTIONS_COMBO = "Combo Actions"
TAB_ACTIONS_OTHER = "Other Actions"
TAB_ACTIONS_SPECIAL = "Special Actions"
TAB_ACTIONS_PARAMETERS = "Actions that take parameters"
TAB_ACTIONS_PARAMETERS_1 = "Use an action:|r<BR/> action=&lt;action/macro name&gt;"
TAB_ACTIONS_PARAMETERS_2 = "Use an action that does not trigger the global cooldown:|r<BR/> |cff40ff40freeAction|r=&lt;action/macro name&gt;"
TAB_ACTIONS_PARAMETERS_3 = "Use a pet action:|r<BR/> |cff40ff40petAction|r=&lt;action&gt;"
TAB_ACTIONS_PARAMETERS_4 = "Use an item in your equipment or inventory:|r<BR/> use=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_5 = "Use an item only if it is equipped:|r<BR/> useEquipped=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_6 = "Use an item in your equipment or inventory that does not trigger the global cooldown:|r<BR/> useFreeItem=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_7 = "Use an item that does not trigger the global cooldown only if it is equipped:|r<BR/> useFreeEquippedItem=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_8 = "Apply an item weapon buff:|r<BR/> apply{MainHand,OffHand}Buff=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_9 = "Equip a weapon in your main hand:|r<BR/> equipMainHand=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_10 = "Equip a weapon in your off hand:|r<BR/> equipOffHand=&lt;itemid/item name&gt;"
TAB_ACTIONS_PARAMETERS_11 = "Echo the message to your chat:|r<BR/> |cff40ff40echo|r=&lt;message&gt;"
TAB_ACTIONS_PARAMETERS_12 = "Say the message in the specified channel:|r<BR/> |cff40ff40sayIn{|cff40ff40Emote, Guild, Minion, Party, Raid, RAID_WARNING, Say, Yell|r}|cff40ff40|r=&lt;message&gt;"
TAB_ACTIONS_PARAMETERS_13 = "Whisper the message to the specified player or unitId:|r<BR/> |cff40ff40whisperTo|r{|cff40ff40playerName, |cff00ffff&lt;UnitId&gt;|r}|cff40ff40|r=&lt;message&gt;"
TAB_ACTIONS_PARAMETERS_14 = "Cancel the specified buff:|r<BR/> |cff40ff40cancelBuff|r=&lt;buff&gt;"
TAB_ACTIONS_PARAMETERS_15 = "Cancel the specified buff by title:|r<BR/> |cff40ff40cancelBuffTitle|r=&lt;buffTitle&gt;"
TAB_ACTIONS_PARAMETERS_16 = "Set the specified form as the default:|r<BR/> |cff40ff40setForm|r=&lt;form name&gt;"
TAB_ACTIONS_PARAMETERS_17 = "Target a specific unit:|r<BR/> |cff40ff40targetUnit|r=|cff00ffff&lt;UnitId&gt;|r"
TAB_ACTIONS_PARAMETERS_18 = "Cast a spell on a specific unit:|r<BR/> |cff40ff40spellTargetUnit|r=|cff00ffff&lt;UnitId&gt;|r"
TAB_ACTIONS_PARAMETERS_19 = "Target a player/creature by their exact name:|r<BR/> |cff40ff40targetByName|r=&lt;exact name&gt;"
TAB_ACTIONS_PARAMETERS_20 = "Perform emote (See |cff8080ffhttp://www.wowwiki.com/API_TYPE_Emotes_Token|r|cffffffff):|r<BR/> |cff40ff40doEmote|r=&lt;emoteToken&gt;"
TAB_ACTIONS_PARAMETERS_21 = "Play sound (See |cff8080ffhttp://www.wowwiki.com/API_PlaySound|r|cffffffff):|r<BR/> |cff40ff40playSound|r=&lt;soundName&gt;"
TAB_ACTIONS_PARAMETERS_22 = "Meta-Actions"
TAB_ACTIONS_PARAMETERS_23 = "Include the contents of the specified form:|r<BR/> includeForm=&lt;form name&gt;<BR/>"
TAB_ACTIONS_PARAMETERS_24 = "Note:|r This does not accept criteria. It must appear on a line by itself. You cannot include a form in itself, nor should you include a form which includes another form which includes the first (e.g. form A includes form B includes form A == BAD)."
TAB_ACTIONS_PARAMETERS_25 = "Call the specified form:|r<BR/> callForm=&lt;form name&gt;<BR/>"
TAB_ACTIONS_PARAMETERS_26 = "This will try to find a usable action in the specified form, if the criteria on the callForm action are satisfied."

TAB_LIST_CRITERIA = "List of recognised criteria"
TAB_CRITERIA_1 = "<BR/>Append zero or more criteria to an action.  All criteria must be true for that action to be used.  List your actions one after another on separate lines.  The first action that matches all criteria is used."
TAB_CRITERIA_2 = "<BR/>Multiple values within curly braces ({}) means choose one or more.  If more than one is chosen, separate them with commas (e.g. ifRace=Human,Gnome) and the criteria will match if any of the choices match.  If a multiple-choice criteria is negated with a \"Not\" (e.g. ifNotRace=Human,Gnome) then the criteria will match only if none of the choices match.  Square brackets ([]) mean the value is optional.  Do NOT leave the curly braces or square brackets in your form."
TAB_CRITERIA_ACTION = "Action Criteria:"
TAB_CRITERIA_SEE_NOTE = "see note"
TAB_CRITERIA_ATTACK = "Attack Criteria:"
TAB_CRITERIA_BUFF_DEBUFF = "Buff/Debuff Criteria:"
TAB_CRITERIA_PLAYER_ONLY = "player only"
TAB_CRITERIA_SEE_NOTES = "see notes"
TAB_CRITERIA_AND = "and"
TAB_CRITERIA_ITEM = "Item Criteria:"
TAB_CRITERIA_PLAYER = "Player Criteria:"
TAB_CRITERIA_PARTY_OR_RAID = "party or raid"
TAB_CRITERIA_PVP_ONLY = "PvP only"
TAB_CRITERIA_PET = "Pet:"
TAB_CRITERIA_PARTY_PET_TARGET = "Player, Pet or Target Criteria:"
TAB_CRITERIA_DEFAULT = "defaults to &lt;5s, "
TAB_CRITERIA_TARGET = "Target Criteria:"
TAB_CRITERIA_NPC_ONLY = "NPC only"
TAB_CRITERIA_WITHIN = "Within"
TAB_CRITERIA_YARDS = "yards"
TAB_CRITERIA_NOT_WORK_BOSS = "Does not work for bosses"
TAB_CRITERIA_CUSTOM_HELP_1 = "|cffffff00Note 1:|r To use -if{Ctrl,Alt,Shift}Down, you MUST remove any existing Ctrl/Alt/Shift key bindings from the Main Menu, Key Bindings. Otherwise the game will intercept the key and LazyScript will not see it."
TAB_CRITERIA_CUSTOM_HELP_2 = "|cffffff00Note 2:|r Always use with -if[Not]TargetFriend since it will return true if the target is not a valid target for the spell."
TAB_CRITERIA_CUSTOM_HELP_3 = "|cffffff00Note 3:|r Within X.Y sec, defaults to 0.3."
TAB_CRITERIA_CUSTOM_HELP_4 = "|cffffff00Note 4:|r The buff/debuff name must be the full name (including capitalization and spaces) of the buff/debuff title as it appears in the tooltip."
TAB_CRITERIA_CUSTOM_HELP_5 = "|cffffff00Note 5:|r XX refers to the number of buff/debuff applications. e.g. -ifTargetHasDebuff&lt;5=sunder"
TAB_CRITERIA_CUSTOM_HELP_6 = "|cffffff00Note 6:|r As of patch 1.12 this only works on unfriendly targets for Rogue (Sinister Strike), Druid (Growl), Hunter (Wing Clip) and Warrior (Rend)."
TAB_CRITERIA_CUSTOM_HELP_7 = "|cffffff00Note 7:|r The ifUsable criteria checks if the action is valid for use at present as per the Blizzard API call IsUsableAction. This does not include cooldown or range checking."
TAB_CRITERIA_CUSTOM_HELP_8 = "|cffffff00Note 8:|r The ifGlobalCooldown criteria requires a specific action to be placed on your action bar so that it may be checked for the global cooldown. It does not have to be on a visible action bar. For each class, the actions are as follows:"
TAB_CRITERIA_CUSTOM_HELP_8_CLASSES = "Rogue: |cffffffffSinister Strike|r<BR/>Druid: |cffffffffMark of the Wild|r<BR/>Hunter: |cffffffffTrack Beasts|r<BR/>Priest: |cffffffffPower Word: Fortitude|r<BR/>Warrior: |cffffffffBattle Shout|r<BR/>Mage: |cffffffffFrost Armor|r<BR/>Warlock: |cffffffffDemon Skin|r<BR/>Shaman: |cffffffffRockbiter Weapon|r<BR/>Paladin: |cffffffffSeal of Righteousness|r"
TAB_CRITERIA_CUSTOM_HELP_9 = "|cffffff00Note 9:|r The |cff00ffff&lt;UnitId&gt;|r can be any valid UnitId sequence as described in &lt;|cff8080ffhttp://www.wowwiki.com/UnitId|r&gt;. For example, player, pet, target, targettarget. Capitalization is not important."
TAB_CRITERIA_CUSTOM_HELP_10 = "|cffffff00Note 10:|r The ifLastUsed timer will perform the action immediately at the start of combat or if you changed targets if the action is available. The ifTimer criteria will first countdown XX seconds after initiating combat or changing targets before performing the action for the first time."
TAB_CRITERIA_CUSTOM_HELP_11 = "|cffffff00Note 11:|r This criteria only detects full blocks and resists. A partial block or resist (\"Joe hits you for 10 damage (5 blocked).\") either on the player or the target will NOT be detected by this criteria."

TAB_LIST_BUFFS_DEBUFFS = "List of known Buffs/Debuffs"
TAB_BUFFS_DEBUFFS_USED = "<BR/>Used with \"if[Not]{Player,Pet,Target}Has{Buff,Debuff}\" and \"if[Not]{Buff,Debuff}Duration{&lt;,&gt;}XXs\".<BR/>"
TAB_FULL_SHORT_NAME = "Full Name = Short Name"

-- FormEdit.xml
LazyScript_Form_Editor = "LazyScript Form Editor"
Editing_form = "Editing form:"
Help = "Help"
Cancel = "Cancel"
Okay = "Okay"
Test = "Test"
LazyScript_Help = "LazyScript Help"
Overview = "Overview"
Actions = "Actions"
Criteria = "Criteria"
Buffs_Debuffs = "Buffs/Debuffs"
Extras = "Extras"
-- Immunity.xml
--Cancel = "Cancel"
--Help = "Help"
--Okay = "Okay"
Immunities_Criteria_Editor = "Immunities Criteria Editor"
Shows_all_learned_immunities = "The following shows all learned immunities so far..."
